spring:
  application:
    name: turbine

server:
  port: 8767
#
#management:
#  port: 8768

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
turbine:
  app-config: ribbon-consumer
  cluster-name-expression: "'default'"
  aggregator:
    cluster-config: default


